apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: indexd-deployment
spec:
  selector:
    # Only select pods based on the 'app' label
    matchLabels:
      app: indexd
      release: production
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: indexd
        release: production
      annotations:
        iam.amazonaws.com/role: bucket_reader_tedtest1-databucket-gen3
    spec:
      nodeName: ip-172-24-68-185.ec2.internal
      tolerations:
        - key: kiam
          value: kiam
          effect: NoSchedule
        - key: role
          value: jupyter
          effect: NoSchedule
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - indexd
              topologyKey: "kubernetes.io/hostname"
      automountServiceAccountToken: false
      volumes:
        - name: config-volume
          secret:
            secretName: "indexd-secret"
        - name: creds-volume
          secret:
            secretName: "indexd-creds"
        - name: config-helper
          configMap:
            name: config-helper
        - name: cert-volume
          secret:
            secretName: "cert-indexd-service"
        - name: ca-volume
          secret:
            secretName: "service-ca"
      containers:
      - name: indexd
        image: quay.io/cdis/indexd:master
        env:
          - name: GEN3_DEBUG
            value: "False"
          - name: DIST
            valueFrom:
              configMapKeyRef:
                name: manifest-indexd
                key: dist
                optional: true
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /_status
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 30
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
          - name: "config-volume"
            readOnly: true
            mountPath: "/var/www/indexd/local_settings.py"
            subPath: "local_settings.py"
          - name: "creds-volume"
            readOnly: true
            mountPath: "/var/www/indexd/creds.json"
            subPath: creds.json
          - name: "config-helper"
            readOnly: true
            mountPath: "/var/www/indexd/config_helper.py"
            subPath: config_helper.py
          - name: "cert-volume"
            readOnly: true
            mountPath: "/mnt/ssl/service.crt"
            subPath: "service.crt"
          - name: "cert-volume"
            readOnly: true
            mountPath: "/mnt/ssl/service.key"
            subPath: "service.key"
          - name: "ca-volume"
            # See https://askubuntu.com/questions/645818/how-to-install-certificates-for-command-line
            readOnly: true
            mountPath: "/usr/local/share/ca-certificates/cdis/cdis-ca.crt"
            subPath: "ca.pem"
        resources:
          limits:
            cpu: 1.0
            memory: 1024Mi
