apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: kiam-agent
spec:
  template:
    metadata:
      # annotations:
      #   prometheus.io/scrape: "true"
      #   prometheus.io/port: "9620"
      labels:
        app: kiam
        role: agent
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      # nodeSelector:
      #   kubernetes.io/role: node
      nodeName: "ip-172-24-68-185.ec2.internal" # Remove after testing
      tolerations: # Remove section after testing
      - key: "kiam"
        operator: "Equal"
        value: "kiam"
        effect: "NoSchedule"
      - key: "role"
        operator: "Equal"
        value: "jupyter"
        effect: "NoSchedule"
      volumes:
        - name: ssl-certs
          hostPath:
            # for AWS linux or RHEL distros
            path: /etc/pki/ca-trust/extracted/pem/
            # path: /usr/share/ca-certificates
        - name: tls
          secret:
            secretName: kiam-agent-tls
        - name: xtables
          hostPath:
            path: /run/xtables.lock
            type: FileOrCreate
      containers:
        - name: kiam
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          image: quay.io/uswitch/kiam:v3.1 # USE A TAGGED RELEASE IN PRODUCTION
          imagePullPolicy: Always
          command:
            - /kiam
          args:
            - agent
            - --iptables
            - --host-interface=!eth0
            - --json-log
            - --port=8181
            - --cert=/etc/kiam/tls/kiam-agent.crt
            - --key=/etc/kiam/tls/kiam-agent.key
            - --ca=/etc/kiam/tls/ca.pem
            - --server-address=kiam-server:443
            - --gateway-timeout-creation=1s
            # - --prometheus-listen-addr=0.0.0.0:9620
            # - --prometheus-sync-interval=5s
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: GRPC_GO_LOG_SEVERITY_LEVEL
              value: "info"
            - name: GRPC_GO_LOG_VERBOSITY_LEVEL
              value: "8"
          volumeMounts:
            - mountPath: /etc/ssl/certs
              name: ssl-certs
            - mountPath: /etc/kiam/tls
              name: tls
            - mountPath: /var/run/xtables.lock
              name: xtables
          livenessProbe:
            httpGet:
              path: /ping
              port: 8181
            initialDelaySeconds: 3
            periodSeconds: 3
